language: node_js
node_js:
  - node
before_install:
  # Updating NPM to relevant version >= 3 on Node.JS LTS
  - npm i -g npm@^3
  - npm install -g @angular/cli
  - npm install -g firebase-tools
  - npm install -g coveralls
install:
  - npm install
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm start &
  - sleep 5
script:
  - ng lint
  - ng test --watch=false --code-coverage=true
  #- npm run e2e
  - ng build --prod --progress=false --aot=false
  - firebase use --token $FIREBASE_DEPLOY_TOKEN $FIREBASE_PROJECT_DEV
  - firebase deploy --token $FIREBASE_DEPLOY_TOKEN -m "ci $TRAVIS_BRANCH build $TRAVIS_BUILD_NUMBER" --non-interactive
after_script:
  - coveralls < ./coverage/coverage.lcov
